# Generated by Django 3.2.8 on 2022-07-28 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL)),
                ('favorited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited', to='tweet.tweet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='favoriteconnection',
            constraint=models.UniqueConstraint(fields=('favorite', 'favorited'), name='favorite_connection_unique'),
        ),
    ]
