# Generated by Django 3.2.8 on 2022-08-12 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0002_auto_20220728_1233'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriteconnection',
            name='favorite_connection_unique',
        ),
        migrations.RemoveField(
            model_name='favoriteconnection',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='favoriteconnection',
            name='favorited',
        ),
        migrations.AddField(
            model_name='favoriteconnection',
            name='favorite_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_account', to='account.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoriteconnection',
            name='favorited_tweet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_tweet', to='tweet.tweet'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='favoriteconnection',
            constraint=models.UniqueConstraint(fields=('favorite_account', 'favorited_tweet'), name='favorite_connection_unique'),
        ),
    ]
