# Generated by Django 3.2.8 on 2022-08-12 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0003_auto_20220812_1500'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriteconnection',
            name='favorite_connection_unique',
        ),
        migrations.RemoveField(
            model_name='favoriteconnection',
            name='favorite_account',
        ),
        migrations.RemoveField(
            model_name='favoriteconnection',
            name='favorited_tweet',
        ),
        migrations.AddField(
            model_name='favoriteconnection',
            name='favorite',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='account.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoriteconnection',
            name='favorited',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorited', to='tweet.tweet'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='favoriteconnection',
            constraint=models.UniqueConstraint(fields=('favorite', 'favorited'), name='favorite_connection_unique'),
        ),
    ]
