# Generated by Django 3.2.7 on 2022-06-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='profile'),
        ),
    ]
