# Generated by Django 3.2.8 on 2022-01-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=200, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password1',
            field=models.CharField(max_length=20, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password2',
            field=models.CharField(max_length=20, verbose_name='パスワードの再入力'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='ユーザー名'),
        ),
    ]
