# Generated by Django 3.2.7 on 2021-11-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterFunc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
