# Generated by Django 3.2.8 on 2022-07-07 05:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_tweet_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 5, 48, 5, 24149, tzinfo=utc), verbose_name='投稿日時'),
        ),
    ]
