# Generated by Django 3.2.8 on 2022-06-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220123_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.TextField(default=1, verbose_name='profile'),
            preserve_default=False,
        ),
    ]
