# Generated by Django 3.2.7 on 2022-07-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_tweet_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
