# Generated by Django 3.2.8 on 2022-07-17 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_followconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followconnection',
            name='following',
        ),
        migrations.AddField(
            model_name='followconnection',
            name='followee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='account.account'),
            preserve_default=False,
        ),
    ]
