# Generated by Django 3.2.7 on 2022-07-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20220717_1350'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='followconnection',
            constraint=models.UniqueConstraint(fields=('follower', 'followee'), name='follow_connection_unique'),
        ),
    ]
